name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup V Language
        uses: vlang/setup-v@v1

      - name: Verify Code Formatting
        run: |
          v fmt -verify *.v
          v fmt -verify demos/*.v
          v fmt -verify tests/*.v
          v fmt -verify tools/*.v
          v fmt -verify scripts/*.vsh
          v fmt -verify examples/*.v

      - name: Run Tests
        run: v test .
